name: Repository Dispatch Handler

on:
  repository_dispatch:
    types:
      - jargon_onRelease

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log the JSON schema content
        id: log-json
        run: |
          echo "Event payload: ${{ toJson(github.event.client_payload) }}"
          
          # Extract JSON schema URLs
          echo "Extracting JSON schemas..."
          JSON_SCHEMAS=$(echo '${{ toJson(github.event.client_payload.artefacts.jsonSchemas) }}' | jq '.')
          echo "JSON Schemas: $JSON_SCHEMAS"
          
          # Iterate and log each schema file name and URL
          for schema in $(echo $JSON_SCHEMAS | jq -c '.[]'); do
            FILE_NAME=$(echo $schema | jq -r '.fileName')
            URL=$(echo $schema | jq -r '.url')
            echo "Schema File: $FILE_NAME, URL: $URL"
          done
          
      - name: Verify JSON schemas
        run: |
          echo "Additional processing can be added here..."
