name: jargon-snapshot

on:
  repository_dispatch:
    types:
      - jargon_onSnapshot

jobs:
  handle-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare working directory
        run: mkdir -p artefacts/snapshots/jsonSchemas

      - name: Download and copy JSON schemas
        run: |
          echo "Extracting JSON schemas from snapshot payload..."
          JSON_SCHEMAS=$(echo '${{ toJson(github.event.client_payload.artefacts.jsonSchemas) }}' | jq -c '.')
          
          for schema in $(echo $JSON_SCHEMAS | jq -c '.[]'); do
            FILE_NAME=$(echo $schema | jq -r '.fileName')
            URL=$(echo $schema | jq -r '.url')
            
            echo "Downloading $FILE_NAME from $URL..."
            curl -L $URL -o "artefacts/snapshots/jsonSchemas/$FILE_NAME"
          done

      - name: List downloaded files
        run: ls -R artefacts/snapshots/jsonSchemas



      - name: Create a new branch
        run: |
          BRANCH_NAME="snapshot-${{ github.event.client_payload.snapshot.index }}-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add artefacts/snapshots/jsonSchemas
          git commit -m "Add JSON schema files from snapshot repository_dispatch event"


      - name: Show git status
        run: git status


      - name: Push branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="snapshot-${{ github.event.client_payload.snapshot.index }}-${{ github.run_id }}"
          git push -u origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: snapshot-${{ github.event.client_payload.snapshot.index }}-${{ github.run_id }}
          base: main
          title: "Snapshot: Add JSON schema files"
          body: |
            This pull request was automatically created by a workflow to add JSON schema files from a snapshot event.

            - **Snapshot Index**: ${{ github.event.client_payload.snapshot.index }}
            - **Description**: ${{ github.event.client_payload.snapshot.description }}
